apiVersion: v2
name: pick-execution-service
description: Pick execution with TSP path optimization
type: application
version: 1.0.0
appVersion: 1.0.0
keywords:
- paklog
- warehouse
- wms
- microservices
maintainers:
- name: Paklog Team
